### ISSUE TITLE
Order Flowers for V-Day

### ISSUE THREAD

**Issue by KimKardashWest** [KimKardashWest/Relationship#17]
I didn’t see a receipt for my valentine’s day flowers come through yet. Just a reminder :blush:

**Comment by KanYeezy** [comment]
I’m just so tired of starting the conversation with flowers…Can’t we ever just start the conversation with love, why don’t we start the conversation with God? Why don’t we start the conversation with family?

**Comment by KimKardashWest** [comment]
So you did order my favorite flowers.

**Comment by KanYeezy** [comment]
![kimsflowers](https://cloud.githubusercontent.com/assets/10948980/6138323/0c3ac89c-b14e-11e4-9320-e457e8433660.jpg)

**Comment by KimKardashWest** [comment]
Babe, that’s a picture from last year. Nice try :wink:

**Comment by KimKardashWest** [comment]
Get out of bed and get my flowers.

![article-0-20348ba900000578-426_634x475](https://cloud.githubusercontent.com/assets/10948982/6138381/a30b6344-b14e-11e4-8a33-837901857749.jpg)

**Comment by KanYeezy** [comment]
OKAY OKAY OKAY :smirk:

**Comment by KimKardashWest** [comment]
You are…You’re the most amazing husband ever.

**Comment by KanYeezy** [comment]
I’m an inventor.

**Comment by KanYeezy** [comment]
Giiiirl traffic is not a joke today! :worried:

**Comment by KimKardashWest** [comment]
That’s why you should have pre-ordered them and had them shipped. Don’t forget to pick up North at 1.

**Comment by KanYeezy** [comment]
What?! I thought you were getting @BabyNorthWest!

**Comment by KimKardashWest** [comment]
You never listen to me! See issue #2. I have a photoshoot today!

**Comment by KimKardashWest** [comment]
OMG I’m getting attacked by an elephant! :scream:

![kim-kardashian-elephant-1](https://cloud.githubusercontent.com/assets/10948982/6138571/461d2382-b150-11e4-9620-6ade3af8c914.gif)

**Comment by BabyNorthWest** [comment]
HAHAHAHAHA

![screen shot 2015-02-10 at 6 15 14 pm](https://cloud.githubusercontent.com/assets/10949033/6138642/d03e0860-b150-11e4-97df-9ea25175ec44.png)

**Comment by KanYeezy** [comment]
My girl, @BabyNorthWest!

**Comment by KanYeezy** [comment]
Picking up your flowers now. They’re out of your favorite. 

![screen shot 2015-02-10 at 6 17 13 pm](https://cloud.githubusercontent.com/assets/10948980/6138682/1611f108-b151-11e4-9479-cb7d6859ac78.png)

**Comment by KimKardashWest** [comment]
But babe you’re an inventor, can’t you invent some?

**Comment by KanYeezy** [comment]
That’s not how it works, @KimKardashWest. I’ve been doin’ this more than you.

**Comment by KrisKardash** [comment]
I told you both not to wait until the last minute...Now you’re going to get wilted ones.

**Comment by KanYeezy** [comment]
@KimKardashWest, don’t you worry about me. I’m picking you up at 7 with the best flowers. Because. That’s. What. I. Do. I take care of my girl, @KrisKardash.

**Comment by KimKardashWest** [comment]
I know, babe! Can’t wait to see you.

**Comment by KanYeezy** [comment]
:smiley: 
![screen shot 2015-02-10 at 6 25 49 pm](https://cloud.githubusercontent.com/assets/10948980/6138806/59e6d97e-b152-11e4-8b55-be5566fffc31.png)

**Comment by KimKardashWest** [comment]
:rage: White Roses. You know this, but we don’t have time now.

**Comment by KrisKardash** [comment]
#tradition

**Comment by KanYeezy** [comment]
:pray:
